version: "3.9"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: disagua
    ports: ["5432:5432"]
    volumes: [ "db_data:/var/lib/postgresql/data" ]
  minio:
    image: quay.io/minio/minio:RELEASE.2024-09-01T00-00-00Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports: ["9000:9000","9001:9001"]
    volumes: [ "minio_data:/data" ]
  createbucket:
    image: minio/mc
    depends_on: [ minio ]
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      mc mb --ignore-existing local/disagua;
      exit 0;
      "
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
volumes:
  db_data:
  minio_data:
